[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
base64 = "0.22.1"
chacha20 = "0.9.1"
dotenvy = "0.15.7"
env_logger = "0.11.5"
log = "0.4.22"
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version = "1.41.0", features = ["full"] }
tokio-tcp = "0.1.4"
