[package]
name = "relay"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20 = "0.9.1"
dotenvy = "0.15.7"
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version = "1.41.0", features = ["full"] }
tokio-tcp = "0.1.4"
