[package]
name = "connector"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chacha20 = "0.9.1"
dotenvy = "0.15.7"
sha2 = "0.10.8"
tokio = { version = "1.41.1", features = ["full"] }
tokio-tcp = "0.1.4"
